import { RecordPlanEntry, PopupIndex } from "../../store.slint";
import { Theme, Icons, Store, Util, Logic } from "../def.slint";
import { NoMessageImg, ConfirmDialogSetting, CenterLayout, TxtEdit, Label, IconBtn, GainFocus, SwitchBtn, Dialog, SkeletonType, Skeleton } from "../../base/widgets.slint";

component HeadBar inherits HorizontalLayout {
    in-out property <int> seleted-index;

    spacing: Theme.spacing * 4;
    height: outer-hbox.preferred-height;

    VerticalLayout {
        alignment: center;
        width: root.width - outer-hbox.preferred-width - parent.spacing;

        HorizontalLayout {
            spacing: Theme.spacing * 4;

            for entry[index] in Store.record-plan-entry.plan: Rectangle {
                visible: self.x + self.width < parent.width;
                width: Theme.icon-size * 1.33;
                height: self.width;
                border-radius: self.width / 2;
                background: entry.is-finished ? Theme.success-color : Theme.secondary-background;
                Label {
                    text: index + 1;
                    color: entry.is-finished ? Theme.base-color : Theme.regular-text-color;
                }
            }
        }
    }

    outer-hbox := HorizontalLayout {
        alignment: end;

        Rectangle {
            height: hbox.preferred-height;
            border-radius: self.height / 2;
            background: Theme.secondary-background;
            border-width: Theme.default-border-width;
            border-color: Theme.base-border-color;

            hbox := HorizontalLayout {
                spacing: Theme.spacing * 4;
                padding: Theme.padding * 2;
                padding-left: Theme.padding * 4;
                padding-right: Theme.padding * 4;

                IconBtn {
                    icon: Icons.ai-robot;
                    hover-color: Store.setting-preference.is-dark ? Theme.secondary-background.darker(50%) : Theme.secondary-background.darker(5%);

                    clicked => {
                        if (Store.record-plan-entry.plan.length == 0) {
                            Logic.ai-generate-record-plans();
                        } else {
                            ConfirmDialogSetting.set(true, Logic.tr("Info"), Logic.tr("Remove all plans and use ai to generate new plans"), "ai-generate-record-plans", "");
                        }
                    }
                }

                IconBtn {
                    icon: Icons.delete-all-light;
                    hover-color: Store.setting-preference.is-dark ? Theme.secondary-background.darker(50%) : Theme.secondary-background.darker(5%);

                    clicked => {
                        ConfirmDialogSetting.set(true, Logic.tr("Warn"), Logic.tr("Remove all entries or not"), "remove-all-record-plans", "");
                    }
                }

                IconBtn {
                    icon: Icons.delete;
                    hover-color: Store.setting-preference.is-dark ? Theme.secondary-background.darker(50%) : Theme.secondary-background.darker(5%);

                    clicked => {
                        if (seleted-index < 0 || seleted-index >= Store.record-plan-entry.plan.length) {
                            return;
                        }
                        ConfirmDialogSetting.set(true, Logic.tr("Warn"), Logic.tr("Remove entry or not"), "remove-record-plan", seleted-index);
                    }
                }

                IconBtn {
                    icon: Icons.add-light;
                    hover-color: Store.setting-preference.is-dark ? Theme.secondary-background.darker(50%) : Theme.secondary-background.darker(5%);

                    clicked => {
                        Logic.add-record-plan();
                    }
                }
            }
        }
    }
}

component BodyItem inherits Rectangle {
    in-out property <int> index;
    in-out property <bool> is-selected;
    in-out property <RecordPlanEntry> entry;

    out property mouse-x <=> move-btn.mouse-x;
    out property mouse-y <=> move-btn.mouse-y;
    out property pressed-x <=> move-btn.pressed-x;
    out property pressed-y <=> move-btn.pressed-y;

    callback head-clicked <=> ta.clicked;
    callback moved <=> move-btn.moved;
    callback pointer-event <=> move-btn.pointer-event;

    border-radius: Theme.border-radius;
    border-color: ta.has-hover || is-selected ? Theme.thirdly-brand-color : Theme.base-border-color;
    border-width: Theme.default-border-width;
    background: Theme.secondary-background;
    height: vbox.preferred-height;

    ta := GainFocus { }

    vbox := VerticalLayout {
        Rectangle {
            HorizontalLayout {
                alignment: space-between;
                padding: Theme.padding * 2;

                Label {
                    font-weight: Theme.bold-font-weight;
                    font-size: Theme.title5-font-size;
                    text: Logic.tr("Step") + " " + (index + 1);
                    color: entry.is-finished ? Theme.success-color : Theme.primary-text-color;
                }

                HorizontalLayout {
                    spacing: Theme.padding * 4;

                    SwitchBtn {
                        checked: entry.is-finished;
                        indicator-size: Theme.icon-size * Theme.golden-ratio;

                        toggled => {
                            entry.is-finished = !entry.is-finished;
                            Logic.update-record-plan(index, entry);
                        }
                    }

                    move-btn := IconBtn {
                        icon: Icons.move;
                        show-icon-hover-background: false;
                        mouse-cursor: self.has-hover ? MouseCursor.move : MouseCursor.default;
                    }
                }
            }
        }

        HorizontalLayout {
            padding: Theme.padding;

            Rectangle {
                height: Theme.default-font-size * 4;
                background: Theme.base-background;

                TxtEdit {
                    text: entry.detail;
                    font-size: Theme.title6-font-size;
                    border-color: Theme.base-border-color;

                    edited(text) => {
                        entry.detail = text;
                        Logic.update-record-plan(index, entry);
                    }
                }
            }
        }
    }
}

component Body inherits Flickable {
    in-out property <int> seleted-index: -1;

    private property <int> moving-index: -1;
    private property <length> item-height;
    private property next-item-pos-y <=> Store.next-record-plan-item-pos-y;

    interactive: false;
    viewport-height: next-item-pos-y;

    public function scroll(rate: float) {
        root.viewport-y = -(root.viewport-height - root.height) * rate;
    }

    init => {
        next-item-pos-y = 0px;
    }

    Rectangle {
        GainFocus {
            clicked => {
                seleted-index = -1;
            }
        }

        for entry[index] in Store.record-plan-entry.plan: BodyItem {
            private property <length> offset-y;

            height: item-height;
            index: index;
            entry: entry;
            is-selected: index == seleted-index || moving-index == index;

            init => {
                if (index == 0) {
                    item-height = self.preferred-height;
                }
                self.y = next-item-pos-y;
                next-item-pos-y += item-height + Theme.spacing * 2;
            }

            head-clicked => {
                if (seleted-index == index) {
                    seleted-index = -1;
                } else {
                    seleted-index = index;
                }
            }

            moved => {
                if (moving-index < 0) {
                    return;
                }
                self.offset-y = self.pressed-y - self.mouse-y;
                self.y = Math.clamp(self.y - self.offset-y, 0, Math.max(root.viewport-height, root.height) - self.height);
            }

            pointer-event(event) => {
                if (event.button == PointerEventButton.left) {
                    if (event.kind == PointerEventKind.down) {
                        moving-index = index;
                    } else {
                        Logic.move-record-plan(moving-index, self.y, item-height + Theme.spacing * 2);
                        moving-index = -1;
                    }
                }
            }
        }
    }
}

export component RecordPlanDialog inherits Dialog {
    title: Logic.tr("Edit Plan");
    is-prevent-event-forward: true;
    is-hide-bottom-btns: true;

    in-out property <length> inner-height: 650px;

    VerticalLayout {
        padding: Theme.padding * 2;
        padding-top: Theme.padding * 4;
        spacing: Theme.spacing * 4;
        height: root.inner-height;

        vbox := VerticalLayout {
            alignment: center;

            hb := HeadBar {
                seleted-index: body.seleted-index;
            }
        }

        hbox := HorizontalLayout {
            height: parent.height - vbox.preferred-height - parent.spacing - parent.padding - parent.padding-top;
            spacing: Theme.spacing * 2;

            private property <bool> is-show-scrollbar: Store.record-plan-entry.plan.length > 0 && body.viewport-height > self.height;

            Rectangle {
                if !Store.is-ai-generate-record-plans && Store.record-plan-entry.plan.length == 0: CenterLayout {
                    NoMessageImg {
                        width: root.width;
                        text: Logic.tr("No Message");
                    }
                }

                if Store.is-ai-generate-record-plans && Store.record-plan-entry.plan.length == 0: Skeleton {
                    y: Theme.padding * 2;
                    type: SkeletonType.List;
                    height: Math.min(200px, hbox.height * 0.4);
                }

                body := Body {
                    visible: Store.record-plan-entry.plan.length > 0;
                    private property <float> scroll-rate;

                    flicked => {
                        if (is-show-scrollbar) {
                            scroll-rate = -self.viewport-y / (self.viewport-height - self.height);
                            sb.y = (parent.height - sb.height) * scroll-rate;
                        }
                    }
                }
            }

            sb := Rectangle {
                visible: is-show-scrollbar;
                background: Theme.placeholder-text-color;
                height: Math.max(parent.height * 0.1, body.height - body.viewport-height + body.height);
                width: Theme.padding * 1.5;
                border-radius: self.width / 2;

                private property <bool> is-scrolling;
                private property <length> offset-y;

                TouchArea {
                    mouse-cursor: self.has-hover ? MouseCursor.pointer : MouseCursor.default;
                    moved => {
                        if (!is-scrolling) {
                            return;
                        }
                        parent.offset-y = self.pressed-y - self.mouse-y;
                        parent.y = Math.clamp(parent.y - parent.offset-y, 0, body.height - parent.height);
                        body.scroll(parent.y / (body.height - parent.height));
                    }

                    pointer-event(event) => {
                        if (event.button == PointerEventButton.left) {
                            if (event.kind == PointerEventKind.down) {
                                is-scrolling = true;
                            } else {
                                is-scrolling = false;
                            }
                        }
                    }
                }
            }
        }
    }

    cancel-clicked => {
        Logic.switch-popup(PopupIndex.None);
    }
}
