import { RecordState, PopupIndex, RecordEntry } from "../../store.slint";
import { Theme, Icons, Store, Util, Logic } from "../def.slint";
import { Date, ToastStatus} from "../../base/def.slint";
import { Search, LineInput, Label, IconBtn, FlashProgress, ConfirmBtn, TextBtnWithoutIcon, GainFocus, DatePickerPopup, Tag, Dialog, SettingDetailInner, SettingDetailInnerVbox, SettingDetailLabel } from "../../base/widgets.slint";

export component RecordEditDialog inherits Dialog {
    title: Store.edit-record-entry.uuid.is-empty ? Logic.tr("New Task") : Logic.tr("Edit Task");
    is-prevent-event-forward: true;

    in-out property <length> inner-height: 650px;

    private property <RecordEntry> clean-entry;
    private property <bool> is-set-start-date;
    private property <Date> current-date: Util.get-current-date();
    private property <string> dp-set-date-str;

    init => {
        if (Store.edit-record-entry.uuid.is-empty) {
            Store.edit-record-entry = clean-entry;
            Store.edit-record-entry.state = RecordState.Running;
            Store.edit-record-entry.start-date = Util.date-str(current-date);
            Store.edit-record-entry.end-date = Util.date-str(current-date);
        }
    }

    vbox := VerticalLayout {
        height: Math.min(root.inner-height, self.preferred-height);

        SettingDetailInner {
            SettingDetailInnerVbox {
                SettingDetailLabel {
                    text: Logic.tr("Start date");
                }

                start-date-lineedit := LineInput {
                    read-only: true;
                    is-show-icon: true;
                    icon: Icons.calender;
                    text: Store.edit-record-entry.start-date;

                    clicked => {
                        is-set-start-date = true;
                        dp-set-date-str = self.text;
                        dp.show();
                    }
                }
            }

            SettingDetailInnerVbox {
                SettingDetailLabel {
                    text: Logic.tr("End date");
                }

                end-date-lineedit := LineInput {
                    read-only: true;
                    is-show-icon: true;
                    icon: Icons.calender;
                    text: Store.edit-record-entry.end-date;

                    clicked => {
                        is-set-start-date = false;
                        dp-set-date-str = self.text;
                        dp.show();
                    }
                }
            }

            SettingDetailInnerVbox {
                SettingDetailLabel {
                    text: Logic.tr("Task name");
                }

                task-name-lineedit := LineInput {
                    is-show-icon: true;
                    icon: Icons.paste;
                    placeholder-text: Logic.tr("Enter task name");
                    text: Store.edit-record-entry.title;

                    clicked => {
                        self.text = Logic.paste-from-clipboard();
                    }
                }
            }

            SettingDetailInnerVbox {
                SettingDetailLabel {
                    text: Logic.tr("Tags");
                }

                tag-lineedit := LineInput {
                    is-show-icon: true;
                    icon: Icons.success;
                    placeholder-text: Logic.tr("Enter tag");

                    function add-tag(tag: string) {
                        if (Store.edit-record-entry.tags.length == 0) {
                            Store.edit-record-entry.tags = [tag];
                        } else if (Store.edit-record-entry.tags.length == 1) {
                            Store.edit-record-entry.tags = [Store.edit-record-entry.tags[0], tag];
                        } else if (Store.edit-record-entry.tags.length == 2) {
                            Store.edit-record-entry.tags = [Store.edit-record-entry.tags[0], Store.edit-record-entry.tags[1], tag];
                        } else {
                            Util.show-toast(Logic.tr("Too many tags. Only support 3 tags."), ToastStatus.Warning);
                            return;
                        }

                        self.text = "";
                    }

                    clicked => {
                        add-tag(self.text);
                        self.focus();
                    }

                    accepted => {
                        add-tag(self.text);
                        self.focus();
                    }
                }

                HorizontalLayout {
                    alignment: center;
                    padding-top: Theme.padding * 2;
                    spacing: Theme.spacing * 4;

                    function tag-name(tags: [string], index: int) -> string {
                        if (index == 0 && tags.length >= 1) {
                            return tags[0];
                        } else if (index == 1 && tags.length >= 2) {
                            return tags[1];
                        } else if (index == 2 && tags.length >= 3) {
                            return tags[2];
                        } else {
                            return "";
                        }
                    }

                    for index in 3: Tag {
                        visible: !self.text.is-empty;
                        text: tag-name(Store.edit-record-entry.tags, index);
                        background: Theme.tag-colors[index];
                        is-show-close-btn: true;
                        font-size: Theme.title5-font-size;

                        close => {
                            if (Store.edit-record-entry.tags.length == 1) {
                                Store.edit-record-entry.tags = [];
                            } else if (Store.edit-record-entry.tags.length == 2) {
                                if (index == 0) {
                                    Store.edit-record-entry.tags = [Store.edit-record-entry.tags[1]];
                                } else {
                                    Store.edit-record-entry.tags = [Store.edit-record-entry.tags[0]];
                                }
                            } else {
                                if (index == 0) {
                                    Store.edit-record-entry.tags = [Store.edit-record-entry.tags[1], Store.edit-record-entry.tags[2]];
                                } else if (index == 1) {
                                    Store.edit-record-entry.tags = [Store.edit-record-entry.tags[0], Store.edit-record-entry.tags[2]];
                                } else {
                                    Store.edit-record-entry.tags = [Store.edit-record-entry.tags[0], Store.edit-record-entry.tags[1]];
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    dp := DatePickerPopup {
        x: (root.width - self.width) / 2;
        y: 50px;

        init => {
            self.set-date(Util.parse-date-str(dp-set-date-str));
        }

        confirmed(date) => {
            if (is-set-start-date) {
                start-date-lineedit.text = Util.date-str(date);
            } else {
                end-date-lineedit.text = Util.date-str(date);
            }
        }
    }

    cancel-clicked => {
        Logic.switch-popup(PopupIndex.None);
    }

    ok-clicked => {
        Store.edit-record-entry.start-date = start-date-lineedit.text;
        Store.edit-record-entry.end-date = end-date-lineedit.text;
        Store.edit-record-entry.title = task-name-lineedit.text;

        if (Logic.remain-days(Store.edit-record-entry.start-date, Store.edit-record-entry.end-date) <= 0) {
            Util.show-toast(Logic.tr("End date should greater than start date"), ToastStatus.Warning);
            return;
        }
        Logic.switch-popup(PopupIndex.None);

        if (Store.edit-record-entry.uuid.is-empty) {
            Logic.new-record(Store.edit-record-entry);
        } else {
            Logic.update-record(Store.edit-record-entry);
        }
    }
}
