import { Theme, Icons, Store, Util, Logic } from "../def.slint";

import { DatePicker, DatePickerPopup, HorizontalLedNumber, VerticalLedNumber } from "../../base/widgets.slint";

export component Statistic inherits VerticalLayout {
    padding: Theme.padding * 8;
    spacing: Theme.spacing * 8;

    HorizontalLayout {
        width: 100%;
        alignment: center;

        VerticalLedNumber {
            number-size: Theme.icon-size;
            numbers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
        }
    }

    HorizontalLayout {
        width: 100%;
        alignment: center;
        HorizontalLedNumber {
            number-size: Theme.icon-size * 2;
            numbers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
        }
    }

    // Rectangle {
    //     width: 100%;
    //     height: 100%;
    //     background: red;

        // TouchArea {
        //     clicked => {
        //         dp.show();
        //     }
        // }
        //
        // dp := DatePickerPopup {
        //     confirmed(date) => {
        //         debug(date);
        //     }
        // }
    // }
}
