import { RecordState } from "../../store.slint";
import { Theme, Icons, Store, Util, Logic } from "../def.slint";
import { IconBtn, FlickableWithScrollBar, DatePicker, DatePickerPopup, Label, HorizontalLedNumber, VerticalLedNumber } from "../../base/widgets.slint";


component SummaryItem inherits VerticalLayout {
    in-out property <int> number;
    in-out property number-color <=> number-label.color;
    in-out property describe <=> describe-label.text;
    in-out property describe-color <=> describe-label.color;

    VerticalLayout {
        spacing: Theme.spacing * 2;
        alignment: center;

        number-label := Label {
            horizontal-alignment: center;
            font-size: Theme.title1-font-size * 2;
            font-weight: Theme.bold-font-weight;
            color: Theme.thirdly-brand-color;
            text: number;
        }

        describe-label := Label {
            horizontal-alignment: center;
            font-size: Theme.title3-font-size;
            color: Theme.placeholder-text-color;
        }
    }
}

component Summary inherits VerticalLayout {
    init => {
        Logic.statistic-init();
    }

    function calc-total-days(_flag: int) -> int {
        return Logic.statistic-total-days-spent(Store.statistic-entries);
    }

    Rectangle {
        height: hbox.preferred-height;
        background: Theme.hover-background;
        border-radius: Theme.border-radius;

        hbox := HorizontalLayout {
            padding: Theme.padding * 4;
            spacing: Theme.spacing * 4;
            alignment: space-around;

            SummaryItem {
                number: Store.statistic-entries.length;
                describe: Logic.tr("Total Tasks");
            }

            total-days := SummaryItem {
                number: calc-total-days(Store.statistic-entries.length);
                number-color: Theme.success-color;
                describe: Logic.tr("Total Days Spent");
            }

            mean-days := SummaryItem {
                number: Store.statistic-entries.length <= 0 ? 0 : total-days.number / Store.statistic-entries.length;
                number-color: Theme.warning-color;
                describe: Logic.tr("Mean Days Spent");
            }
        }
    }
}

export struct ChartBarEntry {
    label: string,
    value: int,
    color: brush,
}

component ChartBar inherits Rectangle {
    in-out property <[ChartBarEntry]> entries;
    in-out property <Orientation> orientation: Orientation.vertical;
    // in-out property <Orientation> orientation: Orientation.horizontal;
    in-out property <string> title;
    in-out property <length> bar-size: Theme.icon-size * 2;
    in-out property <length> axis-size: Theme.default-border-width;
    in-out property <color> axis-color: Theme.regular-text-color;
    in-out property <length> axis-padding: Theme.padding * 8;
    in-out property <angle> label-totation-angle: orientation == Orientation.horizontal ? 0 : 20deg;
    in-out property <angle> number-totation-angle;
    in-out property <bool> is-hide-number-axis;
    in-out property <duration> animate-duration: Theme.default-animate-duration * 2;

    private property <int> max-value-tmp;
    private property <int> max-value: max-value-tmp * 1.2;
    private property <bool> animation-flag;

    Timer {
        interval: 100ms;
        running: true;
        triggered() => {
            animation-flag = true;
            self.running = false;
        }
    }

    vbox := VerticalLayout {
        spacing: Theme.spacing * 4;
        alignment: start;

        title-label := Label {
            text: title;
            horizontal-alignment: center;
            font-size: Theme.title1-font-size;
            font-weight: Theme.bold-font-weight;
        }

        if orientation == Orientation.horizontal: VerticalLayout {
            height: root.height - title-label.preferred-height - vbox.spacing;

            private property <length> viewport-height: self.height - number-labels-vbox.preferred-height;
            private property <length> viewport-width: self.width - labels-vbox.preferred-width - axis-v.width;

            HorizontalLayout {
                alignment: start;

                labels-vbox := VerticalLayout {
                    alignment: space-between;
                    padding: Theme.padding * 2;
                    padding-top: axis-padding;
                    padding-bottom: axis-padding;

                    for entry in entries: HorizontalLayout {
                        alignment: end;
                        height: bar-size;

                        init => {
                            max-value-tmp = Math.max(max-value-tmp, entry.value);
                        }

                        Label {
                            rotation-angle: label-totation-angle;
                            text: entry.label;
                        }
                    }
                }

                axis-v := Rectangle {
                    height: viewport-height;
                    width: axis-size;
                    background: axis-color;
                }

                VerticalLayout {
                    alignment: space-between;
                    padding-top: Theme.padding * 8;
                    padding-bottom: Theme.padding * 8;

                    for entry in entries: HorizontalLayout {
                        alignment: start;
                        height: bar-size;
                        spacing: Theme.spacing * 2;

                        Rectangle {
                            background: entry.color;
                            border-top-right-radius: Theme.border-radius;
                            border-bottom-right-radius: Theme.border-radius;

                            states [
                                animate-running when animation-flag: {
                                    width: Math.max(0, max-value <= 0 ? 0 : (viewport-width - axis-padding) * entry.value / max-value);
                                    in {
                                        animate width { duration: animate-duration; }
                                    }
                                }
                                animate-stop when !animation-flag: {
                                    width: 0;
                                }
                            ]
                        }

                        Label {
                            text: entry.value;
                            color: entry.color;
                        }
                    }
                }
            }

            number-labels-vbox := VerticalLayout {
                visible: !is-hide-number-axis;
                x: axis-v.x;
                width: viewport-width;
                height: is-hide-number-axis ? 0 : self.preferred-height;
                alignment: start;

                Rectangle {
                    height: axis-size;
                    background: axis-color;
                }

                number-hbox := HorizontalLayout {
                    width: number-labels-vbox.width - axis-padding;
                    alignment: space-between;
                    padding: Theme.padding;
                    padding-left: 0;

                    private property <int> number-counts: self.width / (Theme.default-font-size * 4);

                    init => {
                        if (number-counts == 0) {
                            is-hide-number-axis = true;
                        }
                    }

                    for index in number-counts: Label {
                        rotation-angle: number-totation-angle;
                        text: number-counts <= 1 ? 0 : Math.round(max-value / (number-counts - 1) * index);
                    }
                }
            }
        }
    }

    if orientation == Orientation.vertical: HorizontalLayout {
        height: root.height - title-label.preferred-height - vbox.spacing;

        private property <length> viewport-height: self.height - labels-hbox.preferred-height;
        private property <length> viewport-width: self.width - number-hbox2.preferred-width;

        number-hbox2 := HorizontalLayout {
            alignment: start;
            height: viewport-height;

            number-labels-vbox2 := VerticalLayout {
                alignment: space-between;
                padding: Theme.padding * 2;
                padding-top: axis-padding;
                padding-bottom: 0;

                private property <int> number-counts: self.height / (Theme.default-font-size * 4);

                init => {
                    if (number-counts == 0) {
                        is-hide-number-axis = true;
                    }
                }

                for index in number-counts: HorizontalLayout {
                    alignment: end;

                    Label {
                        rotation-angle: number-totation-angle;
                        text: number-counts <= 1 ? 0 : Math.round(max-value / (number-counts - 1) * (number-counts - index - 1));
                    }
                }
            }

            axis-v2 := Rectangle {
                height: viewport-height;
                width: axis-size;
                background: axis-color;
            }
        }

        VerticalLayout {
            alignment: end;
            height: parent.height;

            HorizontalLayout {
                alignment: space-between;
                padding-left: axis-padding;
                padding-right: axis-padding;

                for entry in entries: VerticalLayout {
                    alignment: end;
                    width: bar-size;
                    spacing: Theme.spacing * 2;

                    init => {
                        max-value-tmp = Math.max(max-value-tmp, entry.value);
                    }

                    Label {
                        horizontal-alignment: center;
                        text: entry.value;
                        color: entry.color;
                    }

                    Rectangle {
                        background: entry.color;
                        border-top-left-radius: Theme.border-radius;
                        border-top-right-radius: Theme.border-radius;

                        states [
                            animate-running when animation-flag: {
                                height: Math.max(0, max-value <= 0 ? 0 : (viewport-height - axis-padding) * entry.value / max-value);
                                in {
                                    animate height { duration: animate-duration; }
                                }
                            }
                            animate-stop when !animation-flag: {
                                height: 0;
                            }
                        ]
                    }
                }
            }

            Rectangle {
                height: axis-size;
                width: viewport-width;
                background: axis-color;
            }

            labels-hbox := HorizontalLayout {
                alignment: space-between;
                padding-top: Theme.padding;
                padding-left: axis-padding;
                padding-right: axis-padding;

                for entry in entries: HorizontalLayout {
                    alignment: center;
                    width: bar-size;

                    Label {
                        rotation-origin-x: 0;
                        rotation-angle: label-totation-angle;
                        text: entry.label;
                    }
                }
            }
        }
    }
}

component Chart inherits Rectangle {
    private property <int> current-index;

    if current-index == 0: ChartBar {
        title: Logic.tr("Tasks Count");
        entries: [
            {
                label: Logic.tr("NotStarted"),
                value: 10,
                color: Logic.state-color(RecordState.NotStarted),
            },
            {
                label: Logic.tr("Running"),
                value: 30,
                color: Logic.state-color(RecordState.Running),
            },
            {
                label: Logic.tr("Finished"),
                value: 50,
                color: Logic.state-color(RecordState.Finished),
            },
            {
                label: Logic.tr("Giveup"),
                value: 20,
                color: Logic.state-color(RecordState.Giveup),
            },
            {
                label: Logic.tr("Timeout"),
                value: 5,
                color: Logic.state-color(RecordState.Timeout),
            },
        ];
    }

    if current-index == 1: ChartBar {
        title: Logic.tr("Days Spent");
        entries: [
            {
                label: Logic.tr("NotStarted"),
                value: 10,
                color: Logic.state-color(RecordState.NotStarted),
            },
            {
                label: Logic.tr("Running"),
                value: 30,
                color: Logic.state-color(RecordState.Running),
            },
            {
                label: Logic.tr("Finished"),
                value: 50,
                color: Logic.state-color(RecordState.Finished),
            },
            {
                label: Logic.tr("Giveup"),
                value: 20,
                color: Logic.state-color(RecordState.Giveup),
            },
            {
                label: Logic.tr("Timeout"),
                value: 5,
                color: Logic.state-color(RecordState.Timeout),
            },
        ];
    }

    if current-index == 2: ChartBar {
        title: Logic.tr("Mean Days Spent");
        entries: [
            {
                label: Logic.tr("NotStarted"),
                value: 10,
                color: Logic.state-color(RecordState.NotStarted),
            },
            {
                label: Logic.tr("Running"),
                value: 30,
                color: Logic.state-color(RecordState.Running),
            },
            {
                label: Logic.tr("Finished"),
                value: 50,
                color: Logic.state-color(RecordState.Finished),
            },
            {
                label: Logic.tr("Giveup"),
                value: 20,
                color: Logic.state-color(RecordState.Giveup),
            },
            {
                label: Logic.tr("Timeout"),
                value: 5,
                color: Logic.state-color(RecordState.Timeout),
            },
        ];
    }

    HorizontalLayout {
        alignment: end;
        IconBtn {
            icon-size: Theme.icon-size / Theme.golden-ratio;
            icon: Icons.next-light;

            clicked => {
                current-index = current-index + 1;
                current-index = Math.mod(current-index, 3);
            }
        }
    }
}

export component Statistic inherits VerticalLayout {
    padding: Theme.padding * 2;
    spacing: Theme.spacing * 4;
    Summary { }

    Chart { }
}
