export enum DeviceType {
    Desktop,
    Mobile,
    Web,
}

export enum TabIndex {
    Home,
    Statistic,
    Back,
}

export enum PopupIndex {
    Setting,
    About,
    Donate,
    Help,
    RecordPlan,
    RecordEdit,
    None,
}

export enum SettingDetailIndex {
    Preference,
}

export struct SettingPreference {
    win-width: string,
    win-height: string,
    font-size: string,
    font-family: string,
    language: string,
    always-on-top: bool,
    no-frame: bool,
    is-dark: bool,
}

export struct SettingProxy {
    proxy-type: string,
    http-url: string,
    http-port: string,
    socks5-url: string,
    socks5-port: string,
}

//////////////////////////////// Logic Struct Start ////////////////////////////////

export enum RecordState {
    NotStarted,
    Running,
    Finished,
    Giveup,
    Timeout,
}

export struct RecordEntry{
    uuid: string,
    start-date: string,
    end-date: string,
    title: string,
    plan: string,
    state: RecordState,
    tags: [string],
}

//////////////////////////////// Logic Struct End  ////////////////////////////////

export global Store {
    in-out property <DeviceType> device-type: DeviceType.Desktop;
    in-out property <bool> is-first-run;
    in-out property <bool> is-show-landing-page: false;

    in-out property <TabIndex> previous-tab-index: TabIndex.Home;
    in-out property <TabIndex> current-tab-index: TabIndex.Home;
    in-out property <PopupIndex> current-popup-index: PopupIndex.None;
    in-out property <SettingDetailIndex> current-setting-detail-index: SettingDetailIndex.Preference;

    in-out property <bool> is-cn: setting-preference.language == "cn";
    in-out property <SettingPreference> setting-preference: {
        win-width: 500,
        win-height: 800,
        font-size: "16",
        font-family: "Source Han Sans CN",
        language: "en",
        always-on-top: false,
        no-frame: true,
        is-dark: false,
    };

    //////////////////////////////// Logic Start ////////////////////////////////
    in-out property <RecordEntry> edit-record-entry;

    in-out property <[RecordEntry]> record-entries-cache: [];
    in-out property <[RecordEntry]> record-entries: [
        {
            uuid: "uuid-1",
            start-date: "2025-01-02",
            end-date: "2025-03-02",
            title: "Study Deep Learning. hello world, Study Deep Logic Hoeel world",
            plan: "A simple plane",
            state: RecordState.Running,
            tags: ["Study", "Project", "人物"],
        },
        {
            uuid: "uuid-1",
            start-date: "2025-01-02",
            end-date: "2025-03-02",
            title: "Study Deep Learning. hello world, Study Deep Logic Hoeel world",
            plan: "A simple plane",
            state: RecordState.NotStarted,
            tags: ["Study", "Project", "人物"],
        },
        {
            uuid: "uuid-2",
            start-date: "2025-01-02",
            end-date: "2025-03-02",
            title: "Study Deep Learning. goode",
            plan: "A simple plane",
            state: RecordState.Finished,
            tags: ["Project", "人物"],
        },
        {
            uuid: "uuid-3",
            start-date: "2025-01-02",
            end-date: "2025-03-02",
            title: "中文成为是及时好喝吗节混合论文",
            plan: "A simple plane",
            state: RecordState.Giveup,
            tags: ["人物"],
        },
        {
            uuid: "uuid-4",
            start-date: "2025-01-02",
            end-date: "2025-03-02",
            title: "Study Deep Learning",
            plan: "A simple plane",
            state: RecordState.Timeout,
        }
    ];

    //////////////////////////////// Logic End  ////////////////////////////////
}
